### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by lawkaringithi** [VibandaShops/web-client#5]
Navigation bar scrolls with the page instead of remaining at the top

**Comment by lawkaringithi** [comment]
Navigation bar is now fixed.

**Comment by bomb1e** [comment]
PR?

**Comment by lawkaringithi** [comment]
You've already merged it [171cdc2](https://github.com/VibandaShops/web-client/pull/8/commits/171cdc223b4d2f440a9ff35d69ce1441d4a66c5b)
